### ISSUE TITLE
Track last used nonce to handle transactions in quick succession

### ISSUE THREAD

**Issue by hboon** [alpha-wallet/alpha-wallet-ios#565]
Refer to https://github.com/alpha-wallet/alpha-wallet-android/pull/295

**Comment by James-Sangalli** [comment]
Doesn't seem to be an issue here: https://ropsten.etherscan.io/address/0x0d590124d2faabbbdfa5561ccbf778914a50bcca

**Comment by James-Sangalli** [comment]
Not an issue for us.
