### ISSUE TITLE
Enable debug action for Travis for repo

### ISSUE THREAD

**Issue by hboon** [alpha-wallet/alpha-wallet-ios#590]
Good to have debug flag enabled on alpha-wallet-ios and probably alpha-wallet-android repos.

According to https://docs.travis-ci.com/user/running-build-in-debug-mode/#enabling-debug-mode

> Private repositories have debug mode enabled by default, and no changes need to be made. To limit access to debug, grant users only read access to the repo, and use a fork + PR workflow. For public repositories, we have to enable it on a repository basis.
To enable debug for your public repositories, please email us at support@travis-ci.com and let us know which repositories you want activated.

**Comment by James-Sangalli** [comment]
Done.
