### ISSUE TITLE
some N/A token appears in FIFA asset card after upgrade to test flight 1.0(212)

### ISSUE THREAD

**Issue by zhangzhongnan928** [alpha-wallet/alpha-wallet-ios#593]
0xbc8dAfeacA658Ae0857C80D8Aa6dE4D487577c63
![wechatimg3 1](https://user-images.githubusercontent.com/33795543/44309890-fc51b000-a3ff-11e8-9517-ac6143e25728.jpeg)

0x4C41552485Af22Ed277c221854F97887deA500bC
![wechatimg4 1](https://user-images.githubusercontent.com/33795543/44309904-3753e380-a400-11e8-84ff-105ff7ecb609.jpeg)

It cannot be transferred, we tried, and it failed as below  
https://etherscan.io/tx/0xa01b88c0a60031391ececb6dc90ddc636c7348d74a0624767b2a01c45c993262

**Comment by James-Sangalli** [comment]
@hboon on this, have a hunch it is adding the null tokens
