### ISSUE TITLE
Filter delegate contracts

### ISSUE THREAD

**Issue by James-Sangalli** [alpha-wallet/alpha-wallet-ios#641]
When buying a kitty, it goes through the sales contract and thus adds a null token card to the wallet.

We need to filter this, maybe by checking it against something universal among ERC tokens?

**Comment by hboon** [comment]
Also consider just hardcoding a list of (one, for now) contracts to never be displayed if there’s no good/easy way to generalise this?

**Comment by James-Sangalli** [comment]
@hboon get symbol is universal
