### ISSUE TITLE
1.0.4(217) When transferring ERC 20 tokens, the unit symbol should be changed to ERC 20 token's symbol 

### ISSUE THREAD

**Issue by zhangzhongnan928** [alpha-wallet/alpha-wallet-ios#642]
![2018-08-28 09 43 16](https://user-images.githubusercontent.com/33795543/44695670-dd5db880-aaa6-11e8-8dcd-79c1cf1103d4.jpg)

**Comment by hboon** [comment]
Hiding the ETH button (i.e. restoring its original behavior before this bug was introduced) instead since that's also used for togging between ETH and fiat in similar UI when applied to ether. Keeping it would be confusing if it doesn't behave like a button here.
