### ISSUE TITLE
1.0.4(217) transfer ETH function broken

### ISSUE THREAD

**Issue by zhangzhongnan928** [alpha-wallet/alpha-wallet-ios#643]
I tried to transfer 0.5 eth from 0xbc8dAfeacA658Ae0857C80D8Aa6dE4D487577c63 to 0x37588C2af0984Cd280d122d22b9AD08fF3feF90A multiple times

it changed the receiver address to 0x000000... atomically 
it changed amount to 0 ETH atomically

![2018-08-28 09 43 24](https://user-images.githubusercontent.com/33795543/44696148-e51e5c80-aaa8-11e8-9b1b-34f7fae1a060.jpg)

https://ropsten.etherscan.io/tx/0xcb97b957e86f255468d46cc046f9847db10f05001a275a2268570600965c5c27

**Comment by James-Sangalli** [comment]
@hboon cannot reproduce this on either my iphone or the emulator iphonex

**Comment by zhangzhongnan928** [comment]
then you need to come back, and check my phone.
Regards,
[image: AlphaWallet] <https://awallet.io/>

*Victor Zhang*

[image: AlphaWallet Github] <https://github.com/alpha-wallet> [image:
AlphaWallet Twitter] <https://twitter.com/Alpha_wallet> [image: AlphaWallet
Reddit] <https://www.reddit.com/r/AlphaWallet> [image: AlphaWallet Facebook]
<https://www.facebook.com/AlphaWallet/> [image: AlphaWallet Youtube]
<https://www.youtube.com/channel/UCPP12PQeQmQ4_6qXzNvZw-w/> [image:
AlphaWallet Linkedin] <https://www.linkedin.com/company/%CE%B1wallet/> [image:
AlphaWallet Weibo] <https://weibo.com/AlphaWallet>
Join our Telegram group. <https://t.me/AlphaWalletGroup>

**Comment by hboon** [comment]
@James-Sangalli I'll see if I can figure it out. Can you send me the commit ID this is running on?

**Comment by James-Sangalli** [comment]
@hboon should be this one: 64e7301547f7f5b6419c7fa8a9483f4269ac1ec3

**Comment by zhangzhongnan928** [comment]
it happened after i bought a kitty. Do you think it is something related?

**Comment by zhangzhongnan928** [comment]
no, the 3rd one is different. it is a ERC875 transfer transection.
https://ropsten.etherscan.io/tx/0x21f309dc28190e930b07d04f531255f0abb994b9ea0506cabb908d40b69f1eb7

Regards,
[image: AlphaWallet] <https://awallet.io/>

*Victor Zhang*

[image: AlphaWallet Github] <https://github.com/alpha-wallet> [image:
AlphaWallet Twitter] <https://twitter.com/Alpha_wallet> [image: AlphaWallet
Reddit] <https://www.reddit.com/r/AlphaWallet> [image: AlphaWallet Facebook]
<https://www.facebook.com/AlphaWallet/> [image: AlphaWallet Youtube]
<https://www.youtube.com/channel/UCPP12PQeQmQ4_6qXzNvZw-w/> [image:
AlphaWallet Linkedin] <https://www.linkedin.com/company/%CE%B1wallet/> [image:
AlphaWallet Weibo] <https://weibo.com/AlphaWallet>
Join our Telegram group. <https://t.me/AlphaWalletGroup>

**Comment by James-Sangalli** [comment]
Related #648

**Comment by James-Sangalli** [comment]
```
{
    "dd62ed3e": "allowance(address,address)",
    "095ea7b3": "approve(address,uint256)",
    "70a08231": "balanceOf(address)",
    "18160ddd": "totalSupply()",
    "a9059cbb": "transfer(address,uint256)",
    "23b872dd": "transferFrom(address,address,uint256)"
}
```

Thnks the transaction is ERC20
