### ISSUE TITLE
Auto-detection for tokens at launch should include CryptoKitties

### ISSUE THREAD

**Issue by hboon** [alpha-wallet/alpha-wallet-ios#644]
Relevant: `GetContractInteractions.getContractList`

**Comment by James-Sangalli** [comment]
@hboon please elaborate

**Comment by hboon** [comment]
Appending Victor's wallet to https://api.etherscan.io/api?module=account&action=txlist&address= and `0x06012c8cf97BEaD5deAe237070F9587f8E7A266d` doesn't appear. `0xb1690c08e213a35ed9bab7b318de14420fb57d8c` does though, if we want to special case.

**Comment by James-Sangalli** [comment]
@hboon this is the same issue as trying to get contract's whereby you have tokens but haven't directly transacted with it.

We have not found a good solution in either case as it would involve indexing the entire chain.

**Comment by James-Sangalli** [comment]
As this is an old issue and one we cannot solve in the short term, I am gonna close it.
