### ISSUE TITLE
Blacklist and gray list

### ISSUE THREAD

**Issue by colourful-land** [alpha-wallet/alpha-wallet-ios#648]
Some addresses should be protected

- the address denoted by a public key at the infinite point on elliptic curve can't have a private key.
- practically, 0x0000000 has no corresponding private key, because if someone can find the key for that, he is able to find the key for any given address, meaning hash + elliptic curve cryptography is broken.
- the same can be said to 0x1111....1111 and 0x999999.

Some organisations publicly announce that their private key is lost (e.g. Republic Of Conscience ICO) and any money donated to it is lost forever.

--

We might have a few grey levels but let's first have a hard blacklist where transactions simply can't go through.

**Comment by James-Sangalli** [comment]
@colourful-land can check against all bytes being the same but we rely on 0x0000... for ether transfers to mark that they are not contracts.
