### ISSUE TITLE
Show only titles on Non XML ERC875 asset cards

### ISSUE THREAD

**Issue by James-Sangalli** [alpha-wallet/alpha-wallet-ios#664]
When an ERC875 token does not have an XML file, only show the title and blank out the other fields and icons which would normally have n/a

**Comment by zhangzhongnan928** [comment]
![image](https://user-images.githubusercontent.com/33795543/44900694-dac5c200-ad37-11e8-8920-7d8bd821c3e9.png)

**Comment by hboon** [comment]
@James-Sangalli @zhangzhongnan928 is it worth display the token's bytes32 value?

**Comment by James-Sangalli** [comment]
@hboon not for now, also there would be an array of bytes32

**Comment by hboon** [comment]
@James-Sangalli yeah, but we don't bundle them so there's only 1 per card.
