### ISSUE TITLE
Error message when importing free tokens through MagicLink,the gas is not paid by server and user don't have any eth in his wallet.

### ISSUE THREAD

**Issue by zhangzhongnan928** [alpha-wallet/alpha-wallet-ios#676]
![img_6100](https://user-images.githubusercontent.com/33795543/44971266-8153d200-af87-11e8-8311-3a75b311511b.PNG)

This Error message shows up when user import free tokens through MagicLink, the gas is not paid by server and user don't have any eth in his wallet.

Instead of "Invalid ticket link", It should be "You don't have enough eth to pay for the gas fee of this free token".

**Comment by hboon** [comment]
@James-Sangalli In UniversalLinkCoordinator.importFreeTransfer(query:parameters:), we are getting this from payment server:

> FAILURE: responseSerializationFailed(Alamofire.AFError.ResponseSerializationFailureReason.jsonSerializationFailed(Error Domain=NSCocoaErrorDomain Code=3840 "Invalid value around character 0." UserInfo={NSDebugDescription=Invalid value around character 0.}))

Is it able to return something more specific? The status code = `501` also looks out of place.
