### ISSUE TITLE
Translate "Not connected to the internet, please try again" to Chinese

### ISSUE THREAD

**Issue by hboon** [alpha-wallet/alpha-wallet-ios#707]
Please help translate "Not connected to the internet, please try again". Shown when user taps a MagicLink but has no internet connection.

at: https://github.com/alpha-wallet/alpha-wallet-ios/blob/master/AlphaWallet/Localization/zh-Hans.lproj/Localizable.strings#L257

**Comment by zhangzhongnan928** [comment]
@bootingman

**Comment by hboon** [comment]
@bootingman bump.

**Comment by bootingman** [comment]
sorry, missed Github issues, I updated it
