### ISSUE TITLE
Override Asset Definition Files for Development

### ISSUE THREAD

**Issue by hboon** [alpha-wallet/alpha-wallet-ios#716]
Instead of iTunes File Sharing, we can also (A) use iOS/macOS AirDrop.

1. User AirDrops XML file from iOS/macOS to the target iOS device
2. Pop up appears on target device.
3. User choose AlphaWallet in the pop up's list of apps
4. App saves the file into the override directory and things should just work because the override logic was already built earlier.
We need to add some UI in Settings to allow user to remove the override file by contract address. User has to re-transmit the file to update.

(B) Alternatively, we can provide a text box in Settings to key in a URL to the XML file and a button that says `Override` and another that says `Remove override`. The user hits the `Override` button to re-download the file.

Worth also considering if this is required to work, say, in a workshop.

**Comment by James-Sangalli** [comment]
@hboon this is less of an issue for now as we can use android for debugging. This should work but it might cause problems where it works on Android but not iOS

**Comment by hboon** [comment]
> This should work but it might cause problems where it works on Android but not iOS

Can you please elaborate? There's a few ways to read that ^

**Comment by James-Sangalli** [comment]
@hboon the testers might have it working on Android (the XML) but due to discrepancies, it might not work in iOS.
