### ISSUE TITLE
Transactions tab only displaying "normal" transactions, i.e. excludes ERC20s

### ISSUE THREAD

**Issue by hboon** [alpha-wallet/alpha-wallet-ios#720]
According to https://etherscan.io/apis#accounts:

"Normal":

http://api.etherscan.io/api?module=account&action=txlist&address=0xddbd2b932c763ba5b1b7ae3b362eac3e8d40121a&startblock=0&endblock=99999999&sort=asc&apikey=YourApiKeyToken

ERC20:

http://api.etherscan.io/api?module=account&action=tokentx&address=0x4e83362442b8d1bec281594cea3050c8eb01311c&startblock=0&endblock=999999999&sort=asc&apikey=YourApiKeyToken

Looks like we'll need to make 2 separate calls and combine them.

Need to verify for ERC721/ERC875.

**Comment by James-Sangalli** [comment]
@hboon this is not a problem, the api call includes transactions to contracts. We can switch to RPC however.
