### ISSUE TITLE
Translate notification text shown when receiving ether

### ISSUE THREAD

**Issue by hboon** [alpha-wallet/alpha-wallet-ios#729]
These 2 lines:

    "transactions.received.ether" = "You have received %@ ETH";
    "transactions.received.ether.notification.prompt" = "Allow Notifications When You Receive Ether?";

The first line appears as a notification when the user receives ether while app is active.

The second line appears in a dialog with `OK`/`Cancel`, if the user taps `OK`, the app will show the standard iOS notification permission dialog which we can't change the text. Showing a prompt with this second line gives the user some context of how notification is used so they are more likely to approve the notification permission request.

At: https://github.com/alpha-wallet/alpha-wallet-ios/blob/master/AlphaWallet/Localization/zh-Hans.lproj/Localizable.strings#L69

**Comment by bootingman** [comment]
updated
