### ISSUE TITLE
Says purchase when import is free 

### ISSUE THREAD

**Issue by James-Sangalli** [alpha-wallet/alpha-wallet-ios#737]

**Comment by hboon** [comment]
@James-Sangalli related to #702 ?

**Comment by James-Sangalli** [comment]
@hboon opps! This is easy to misunderstand, I mean that the free import should say free import rather than purchase

**Comment by hboon** [comment]
@James-Sangalli Should we change it to say "Import" (and the user be charged the transaction fee)? The total cost says 0 ETH though. Is that understood?

**Comment by James-Sangalli** [comment]
@hboon when it is free it can be import, when you have to pay gas then it is purchase

**Comment by James-Sangalli** [comment]
My bad, turns out that the token I was using was no longer supported by the payment server.
