### ISSUE TITLE
Enable SNS services for push notifications

### ISSUE THREAD

**Issue by James-Sangalli** [alpha-wallet/alpha-wallet-ios#745]

**Comment by James-Sangalli** [comment]
@hboon 

Code in branch "amazon-sns-notifications" allows for registering with the amazon SNS panel using the device token but it has the following issues which I will need you help with:  

- The Notification callback is not being called when a notification is sent from the panel despite being registered and having push notifications enabled in the profile
- Register code is placed inside a function with the same signature that contains realm delegates

Since a lot of this requires working with the Amazon panel, we can rectify the issues tomorrow in person, just wanted to give you a heads up.

**Comment by hboon** [comment]
@James-Sangalli ok! thanks.
